site_name: EEG Robot Control
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy
    - navigation.sections
    - navigation.expand

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Hardware Setup: hardware.md
  - Software Setup: software.md
  - Usage:
      - EEG Integration: eeg.md
      - mBot Control: mbot.md
  - Contributing: contributing.md