site_name: EEG Robot Control
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - toc.integrate


markdown_extensions:
  - attr_list


nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Hardware Setup: hardware.md
  - Software Setup: software.md