site_name: EEG Robot Control
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - toc.integrate


markdown_extensions:
  - attr_list

site_name: '<img src="/Users/khushee/Documents/Arduino/serialReadRobot/EEG-Robot-Control/EEGRobotControl/docs/banner.png" alt="EEG Robot Control" height="50">'
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Hardware Setup: hardware.md
  - Software Setup: software.md
  - The Final Prodcut: final-product.md